---
name: 'tagged-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: 'Tagged Release'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Install dependencies'
        run: npm install --legacy-peer-deps
      - run: npm run lint:lib
      - run: npm run test:lib
      - run: npm run build:lib

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          id: 'automatic_releases'
